apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    name: gateway-service
    app: microservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: gateway
    type: microservice