apiVersion: v1
kind: Pod
metadata:
  name: microservice-seguridad-pod
  lables:
    app: microservice-seguridad
    type: microservice
spec:
  containers:
    - name: microservice-seguridad-app
      image: babellearning/identityapi:latest
      ports:
        - containerPort:80
      env:
        - name: ConnectionStrings__DefaultConnection
          value: Server=mssql-service;Database=Ecommerce;User=sa;Password=$BabelLerarning2021