apiVersion: v1
kind: Pod
metadata:
  name: microservice-libreria-pod
  lables:
    app: microservice-libreria
    type: microservice
spec:
  containers:
    - name: microservice-libreria-app
      image: babellearning/serviciosapilibreria:latest
      ports:
        - containerPort:80
      env:
        - name: MongoDb__ConnectionString
          value: mongodb://babellearning:$BabelLearning2021@mongo-service:27017