apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  lables:
    app: microservice-libreria
    name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo:latest
      command:
      - /bin/bash
      - -c
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "babellearning"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "$BabelLearning2021"
      ports:
        - containerPort: 27017